spring:
  h2:
    console:
      enabled: true

  datasource:
#    url: jdbc:h2:tcp://localhost/~/testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
    url: jdbc:mariadb://svc.sel3.cloudtype.app:30517/ntdb?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234

  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

logging:
  level:
    com.tutorial: debug

# HS512 ????? ??? ??? ??? 512bit, ? 64byte ??? secret key? ???? ??.
# Secret ?? ?? ???? Base64 ? ???? ? ?? (?? ???? ???? ??? ??? ??)
# $ echo 'spring-boot-security-jwt-tutorial-jiwoon-spring-boot-security-jwt-tutorial' | base64
jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK

