spring:
  h2:
    console:
      enabled: true

  datasource:
#    url: jdbc:h2:tcp://localhost/~/testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#    url: jdbc:mariadb://localhost:3306/ntdb?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    url: jdbc:mariadb://localhost:3306/ntdb?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234

  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB

logging:
  level:
    com.tutorial: debug

#server:
#  tomcat:
#    relaxed-query-chars: ['[',']']

# HS512 ????? ??? ??? ??? 512bit ? 64byte ??? secret key? ???? ??.
# Secret ?? ?? ???? Base64 ? ???? ? ?? (?? ???? ???? ??? ??? ??)
# $ echo 'spring-boot-security-jwt-tutorial-jiwoon-spring-boot-security-jwt-tutorial' | base64
jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK

